# This is a basic workflow to help you get started with Actions

name: Release to Nuget

# Controls when the workflow will run
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy: 
        matrix:
            dotnet-version: [ '9.0.x']  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        
      - name: Build Project
        run: dotnet build --configuration Release /p:Version=${VERSION}
      
      - name: Create the package
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .

      - name: Publish the package to Repository
        run: dotnet nuget push UmbracoDayOfWeek.${VERSION}.nupkg --api-key ${NUGET_API_KEY} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}