# This is a basic workflow to help you get started with Actions

name: Release to Nuget

# Controls when the workflow will run
on: [push]

env:
  PROJECT_FOLDER: UmbracoDayOfWeek
  PROJECT: UmbracoDayOfWeek.csproj
  NUGET_REPO_URL: https://nuget.pkg.github.com/Frost117/index.json

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy: 
        matrix:
            dotnet-version: [ '9.0.x']  
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Install Dependencies
        run: dotnet restore $PROJECT_FOLDER/$PROJECT

      - name: Build Project
        run: dotnet build $PROJECT_FOLDER/$PROJECT
      
      - name: Create the package
        run: dotnet pack --configuration Release $PROJECT_FOLDER/$PROJECT

      - name: Publish the package to Rository
        run: dotnet nuget push $PROJECT_FOLDER/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s $NUGET_REPO_URL
